"""
VyaparPro — PDF Generation Engine
Generates print-ready PDFs for invoices, quotations, POs, delivery challans.
Uses ReportLab. Returns bytes for direct HTTP response or S3 upload.
"""
from __future__ import annotations

import io
from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from app.utils.gst_calculator import amount_in_words
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"
try:
    pdfmetrics.registerFont(TTFont("NotoSans", "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf"))
    pdfmetrics.registerFont(TTFont("NotoSans-Bold", "/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf"))
    FONT_REGULAR = "NotoSans"
    FONT_BOLD = "NotoSans-Bold"
except Exception:
    pass

# ── Brand colours ─────────────────────────────────────────────────────────────
BRAND_BLUE  = colors.HexColor("#0066CC")
BRAND_DARK  = colors.HexColor("#1A1A2E")
BRAND_ACCENT = colors.HexColor("#00C2A8")
BG_SOFT      = colors.HexColor("#F0F4FA")
GOOD_GREEN   = colors.HexColor("#0E9F6E")
WARN_ORANGE  = colors.HexColor("#E8720C")
BAD_RED      = colors.HexColor("#DC2626")
LIGHT_GREY  = colors.HexColor("#F5F5F5")
MED_GREY    = colors.HexColor("#CCCCCC")
TEXT_DARK   = colors.HexColor("#212121")


@dataclass
class PDFDocumentData:
    """All data needed to render any billing PDF."""
    doc_type: str           # invoice|quotation|po|delivery_challan|credit_note|debit_note
    doc_no: str
    doc_date: date
    due_date: Optional[date] = None
    # Seller
    company_name: str = ""
    company_gstin: str = ""
    company_address: str = ""
    company_phone: str = ""
    company_email: str = ""
    company_logo_url: Optional[str] = None
    # Buyer
    party_name: str = ""
    party_gstin: str = ""
    party_address: str = ""
    party_phone: str = ""
    party_email: str = ""
    # Optional references
    po_no: Optional[str] = None
    po_date: Optional[date] = None
    jo_no: Optional[str] = None
    status: str = ""  # 'paid' | 'unpaid' | 'overdue' | 'draft' etc — drives the status badge
    place_of_supply: str = ""
    supply_type: str = "intra"
    # Line items
    items: list[dict] = field(default_factory=list)
    # Totals
    subtotal: Decimal = Decimal("0")
    discount_amount: Decimal = Decimal("0")
    taxable_amount: Decimal = Decimal("0")
    cgst_amount: Decimal = Decimal("0")
    sgst_amount: Decimal = Decimal("0")
    igst_amount: Decimal = Decimal("0")
    cess_amount: Decimal = Decimal("0")
    other_charges: Decimal = Decimal("0")
    tds_amount: Decimal = Decimal("0")
    round_off: Decimal = Decimal("0")
    total_amount: Decimal = Decimal("0")
    # IRN / E-invoice
    irn: Optional[str] = None
    ack_no: Optional[str] = None
    ack_date: Optional[datetime] = None
    qr_code_data: Optional[str] = None
    # Misc
    notes: str = ""
    terms_conditions: str = ""
    bank_name: str = ""
    bank_account_no: str = ""
    bank_ifsc: str = ""
    bank_branch: str = ""
    hsn_summary: list[dict] = field(default_factory=list)
    company_pan: str = ""
    eway_bill_no: str = ""
    transporter_name: str = ""
    transporter_id: str = ""
    vehicle_no: str = ""
    challan_no: str = ""
    challan_date: Optional[date] = None
    upi_id: str = ""
    copy_label: str = "ORIGINAL FOR RECIPIENT"


def _fmt(v) -> str:
    """Indian numbering, non-breaking: ₹17,84,963.00"""
    v = float(v or 0)
    neg = v < 0
    v = abs(v)
    whole, _, frac = f"{v:,.2f}".partition(".")
    whole = whole.replace(",", "")
    if len(whole) > 3:
        last3, rest = whole[-3:], whole[:-3]
        groups = []
        while len(rest) > 2:
            groups.insert(0, rest[-2:])
            rest = rest[:-2]
        if rest:
            groups.insert(0, rest)
        whole = ",".join(groups) + "," + last3
    return f"{'-' if neg else ''}₹{whole}.{frac}"

def _footer(canvas, doc):
    canvas.saveState()
    page_w, _ = A4
    canvas.setFillColor(colors.HexColor("#999999"))
    canvas.setFont(FONT_REGULAR, 7)
    canvas.drawString(12*mm, 8*mm, "Generated by VyaparPro ERP · Confidential")
    canvas.drawRightString(page_w - 12*mm, 8*mm, f"Page {doc.page}")
    canvas.restoreState()


from reportlab.graphics.barcode.qr import QrCodeWidget
from reportlab.graphics.shapes import Drawing
from reportlab.graphics import renderPDF


def _qr_drawing(data: str, size: float = 26*mm) -> Drawing:
    qr = QrCodeWidget(data)
    b = qr.getBounds()
    w, h = b[2]-b[0], b[3]-b[1]
    d = Drawing(size, size, transform=[size/w, 0, 0, size/h, 0, 0])
    d.add(qr)
    return d


def generate_invoice_pdf(data: PDFDocumentData) -> bytes:
    """Classic bordered-grid GST tax invoice — matches standard Indian invoicing format."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=8*mm, leftMargin=8*mm,
                             topMargin=8*mm, bottomMargin=8*mm)
    styles = getSampleStyleSheet()
    BORDER = colors.black

    h_company = ParagraphStyle("hco", fontName=FONT_BOLD, fontSize=17, textColor=BRAND_DARK)
    h_tagline = ParagraphStyle("htag", fontName=FONT_BOLD, fontSize=9, textColor=colors.white, alignment=TA_CENTER)
    contact = ParagraphStyle("contact", fontName=FONT_REGULAR, fontSize=8, textColor=TEXT_DARK, leading=11)
    contact_r = ParagraphStyle("contactr", parent=contact, alignment=TA_RIGHT)
    doclabel = ParagraphStyle("doclabel", fontName=FONT_BOLD, fontSize=15, alignment=TA_CENTER)
    label8 = ParagraphStyle("label8", fontName=FONT_BOLD, fontSize=8)
    body8 = ParagraphStyle("body8", fontName=FONT_REGULAR, fontSize=8, leading=11)
    section_hdr = ParagraphStyle("sechdr", fontName=FONT_BOLD, fontSize=8, alignment=TA_CENTER)
    small = ParagraphStyle("small", fontName=FONT_REGULAR, fontSize=7)

    doc_label = {
        "invoice": "TAX INVOICE", "quotation": "QUOTATION", "po": "PURCHASE ORDER",
        "delivery_challan": "DELIVERY CHALLAN", "credit_note": "CREDIT NOTE",
        "debit_note": "DEBIT NOTE", "proforma": "PROFORMA INVOICE",
        "purchase_return": "PURCHASE RETURN / DEBIT NOTE",
    }.get(data.doc_type, data.doc_type.upper().replace("_", " "))

    story = []

    # ── Company header band ─────────────────────────────────────────
    header_inner = Table([
        [Paragraph(data.company_name or "Company Name", h_company), ""],
    ], colWidths=[183*mm])
    story.append(header_inner)
    tagline_band = Table([[Paragraph((data.company_email or data.company_website or " ").upper() if False else " ", h_tagline)]], colWidths=[183*mm])
    addr_row = Table([[
        Paragraph((data.company_address or "").replace("\n", "<br/>"), contact),
        Paragraph(f"Tel: {data.company_phone}<br/>Email: {data.company_email}" if (data.company_phone or data.company_email) else "", contact_r),
    ]], colWidths=[100*mm, 83*mm])
    addr_row.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP")]))
    story.append(addr_row)
    story.append(Spacer(1, 2*mm))

    # ── Doc-type title strip: PAN | TAX INVOICE | Copy label ─────────
    title_strip = Table([[
        Paragraph(f"<b>PAN: {data.company_pan}</b>" if data.company_pan else "", label8),
        Paragraph(f"<b>{doc_label}</b>", doclabel),
        Paragraph(f"<b>{data.copy_label}</b>", ParagraphStyle("copylbl", fontName=FONT_BOLD, fontSize=8, alignment=TA_RIGHT)),
    ]], colWidths=[55*mm, 73*mm, 55*mm])
    title_strip.setStyle(TableStyle([
        ("BOX", (0,0), (-1,-1), 1, BORDER), ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("TOPPADDING",(0,0),(-1,-1),4), ("BOTTOMPADDING",(0,0),(-1,-1),4),
    ]))
    story.append(title_strip)

    # ── Customer Detail | Invoice/Transport Detail (2-col bordered box) ──
    cust_lines = [
        [Paragraph("<b>M/S</b>", label8), Paragraph(data.party_name, body8)],
        [Paragraph("<b>Address</b>", label8), Paragraph((data.party_address or "").replace("\n","<br/>"), body8)],
        [Paragraph("<b>Phone</b>", label8), Paragraph(data.party_phone or "—", body8)],
        [Paragraph("<b>GSTIN</b>", label8), Paragraph(data.party_gstin or "Unregistered", body8)],
        [Paragraph("<b>Place of Supply</b>", label8), Paragraph(data.place_of_supply or "—", body8)],
    ]
    cust_box = Table([[Paragraph("<b>Customer Detail</b>", section_hdr)]] + [[Table(cust_lines, colWidths=[26*mm, 65*mm])]],
                      colWidths=[91*mm])
    cust_box.setStyle(TableStyle([("BOX",(0,0),(-1,-1),1,BORDER), ("LINEBELOW",(0,0),(-1,0),0.5,BORDER),
                                   ("TOPPADDING",(0,0),(-1,-1),3), ("BOTTOMPADDING",(0,0),(-1,-1),3)]))

    meta_rows = [["Invoice No.", f"<b>{data.doc_no}</b>", "Invoice Date", str(data.doc_date)]]
    if data.challan_no: meta_rows.append(["Challan No", data.challan_no, "Challan Date", str(data.challan_date or "")])
    if data.eway_bill_no: meta_rows.append(["E-Way Bill No.", data.eway_bill_no, "", ""])
    if data.transporter_name: meta_rows.append(["Transport", data.transporter_name, "", ""])
    if data.transporter_id: meta_rows.append(["Transport ID", data.transporter_id, "", ""])
    if data.vehicle_no: meta_rows.append(["Vehicle No.", data.vehicle_no, "", ""])
    if data.po_no: meta_rows.append(["PO No.", data.po_no, "PO Date", str(data.po_date or "")])
    meta_table_rows = [[Paragraph(c, label8) if i%2==0 else Paragraph(c, body8) for i,c in enumerate(row)] for row in meta_rows]
    meta_box = Table([[Paragraph("&nbsp;", section_hdr)]] + [[Table(meta_table_rows, colWidths=[22*mm,22*mm,22*mm,26*mm])]], colWidths=[92*mm])
    meta_box.setStyle(TableStyle([("BOX",(0,0),(-1,-1),1,BORDER), ("TOPPADDING",(0,0),(-1,-1),3), ("BOTTOMPADDING",(0,0),(-1,-1),3)]))

    two_col = Table([[cust_box, meta_box]], colWidths=[91*mm, 92*mm])
    two_col.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"), ("LEFTPADDING",(0,0),(-1,-1),0), ("RIGHTPADDING",(0,0),(-1,-1),0)]))
    story.append(two_col)

    # ── IRN strip (if e-invoiced) ──────────────────────────────────
    if data.irn:
        irn_text = f"<b>IRN-</b> {data.irn} | <b>Ack No.-</b> {data.ack_no or '—'} | <b>Ack Date-</b> {data.ack_date or '—'}"
        irn_strip = Table([[Paragraph(irn_text, ParagraphStyle("irn", fontName=FONT_REGULAR, fontSize=6.5))]], colWidths=[183*mm])
        irn_strip.setStyle(TableStyle([("BOX",(0,0),(-1,-1),1,BORDER), ("TOPPADDING",(0,0),(-1,-1),3), ("BOTTOMPADDING",(0,0),(-1,-1),3)]))
        story.append(irn_strip)

    # ── Items table ──────────────────────────────────────────────
    is_igst = data.igst_amount > 0
    if is_igst:
        col_headers = ["Sr.\nNo.", "Name of Product/Service", "HSN/\nSAC", "Qty", "Rate", "Taxable\nValue", "IGST %", "IGST Amt", "Total"]
        col_widths = [8, 55, 14, 12, 18, 20, 12, 18, 26]
    else:
        col_headers = ["Sr.\nNo.", "Name of Product/Service", "HSN/\nSAC", "Qty", "Rate", "Taxable\nValue", "CGST\n%", "CGST\nAmt", "SGST\n%", "SGST\nAmt", "Total"]
        col_widths = [7, 44, 12, 9, 15, 18, 8, 13, 8, 13, 20]
    col_widths = [w * mm for w in col_widths]
    header_style = ParagraphStyle("colh", fontName=FONT_BOLD, fontSize=7, alignment=TA_CENTER, leading=8)

    item_rows = [[Paragraph(h, header_style) for h in col_headers]]
    for item in data.items:
        common = [str(item.get("line_no","")), item.get("description",""), item.get("hsn_code",""),
                  str(item.get("quantity","")), _fmt(item.get("rate",0),""), _fmt(item.get("taxable_amount",0),"")]
        if is_igst:
            tail = [f"{item.get('gst_rate',0):g}", _fmt(item.get("igst_amount",0),"")]
        else:
            half = float(item.get("gst_rate",0))/2
            tail = [f"{half:g}", _fmt(item.get("cgst_amount",0),""), f"{half:g}", _fmt(item.get("sgst_amount",0),"")]
        item_rows.append(common + tail + [_fmt(item.get("total_amount",0),"")])

    items_table = Table(item_rows, colWidths=col_widths, repeatRows=1)
    items_table.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),0.5,BORDER), ("FONTNAME",(0,1),(-1,-1),FONT_REGULAR), ("FONTSIZE",(0,1),(-1,-1),7.5),
        ("ALIGN",(0,0),(0,-1),"CENTER"), ("ALIGN",(3,1),(-1,-1),"RIGHT"),
        ("VALIGN",(0,0),(-1,-1),"TOP"), ("TOPPADDING",(0,0),(-1,-1),3), ("BOTTOMPADDING",(0,0),(-1,-1),3),
    ]))
    story.append(items_table)

    # ── Totals row (grid-attached, not floating) ────────────────────
    total_qty = sum(float(i.get("quantity",0)) for i in data.items)
    if is_igst:
        total_row = [["", "Total", "", f"{total_qty:g}", "", _fmt(data.taxable_amount,""), "", _fmt(data.igst_amount,""), _fmt(data.total_amount,"")]]
        tw = col_widths
    else:
        total_row = [["", "Total", "", f"{total_qty:g}", "", _fmt(data.taxable_amount,""), "", _fmt(data.cgst_amount,""), "", _fmt(data.sgst_amount,""), _fmt(data.total_amount,"")]]
        tw = col_widths
    tot_table = Table(total_row, colWidths=tw)
    tot_table.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),0.5,BORDER), ("FONTNAME",(0,0),(-1,-1),FONT_BOLD), ("FONTSIZE",(0,0),(-1,-1),8),
        ("ALIGN",(3,0),(-1,-1),"RIGHT"), ("TOPPADDING",(0,0),(-1,-1),4), ("BOTTOMPADDING",(0,0),(-1,-1),4),
    ]))
    story.append(tot_table)
    story.append(Spacer(1, 1))

    # ── Total in words | Tax summary box ─────────────────────────
    words_cell = Table([
        [Paragraph("<b>Total in words</b>", section_hdr)],
        [Paragraph(amount_in_words(data.total_amount).upper(), body8)],
    ], colWidths=[110*mm])
    words_cell.setStyle(TableStyle([("BOX",(0,0),(-1,-1),1,BORDER), ("LINEBELOW",(0,0),(-1,0),0.5,BORDER),
                                     ("TOPPADDING",(0,0),(-1,-1),5), ("BOTTOMPADDING",(0,0),(-1,-1),5)]))

    tax_rows = [["Taxable Amount", _fmt(data.taxable_amount)]]
    if is_igst:
        tax_rows.append(["Add: IGST", _fmt(data.igst_amount)])
    else:
        tax_rows.append(["Add: CGST", _fmt(data.cgst_amount)])
        tax_rows.append(["Add: SGST", _fmt(data.sgst_amount)])
    if data.round_off: tax_rows.append(["Round Off", _fmt(data.round_off)])
    tax_rows.append(["Total Tax", _fmt(float(data.cgst_amount)+float(data.sgst_amount)+float(data.igst_amount))])
    tax_rows.append(["Total Amount After Tax", _fmt(data.total_amount)])
    tax_para = [[Paragraph(r[0], body8), Paragraph(f"<b>{r[1]}</b>" if r[0]=="Total Amount After Tax" else r[1],
                 ParagraphStyle("tval", fontName=FONT_BOLD if r[0]=="Total Amount After Tax" else FONT_REGULAR,
                                fontSize=10 if r[0]=="Total Amount After Tax" else 8, alignment=TA_RIGHT))] for r in tax_rows]
    tax_box = Table(tax_para, colWidths=[45*mm, 28*mm])
    tax_box.setStyle(TableStyle([("BOX",(0,0),(-1,-1),1,BORDER), ("LINEABOVE",(0,-1),(-1,-1),0.8,BORDER),
                                  ("TOPPADDING",(0,0),(-1,-1),3), ("BOTTOMPADDING",(0,0),(-1,-1),3)]))

    words_tax_row = Table([[words_cell, tax_box]], colWidths=[110*mm, 73*mm])
    words_tax_row.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"), ("LEFTPADDING",(0,0),(-1,-1),0), ("RIGHTPADDING",(0,0),(-1,-1),0)]))
    story.append(words_tax_row)

    # ── Bank Details + QR (left) | Certification + Signature (right) ──
    bank_lines = []
    if data.bank_name:
        bank_lines = [
            [Paragraph("Name", label8), Paragraph(data.bank_name, body8)],
            [Paragraph("Branch", label8), Paragraph(data.bank_branch or "—", body8)],
            [Paragraph("Acc. Number", label8), Paragraph(data.bank_account_no or "—", body8)],
            [Paragraph("IFSC", label8), Paragraph(data.bank_ifsc or "—", body8)],
        ]
        if data.upi_id:
            bank_lines.append([Paragraph("UPI ID", label8), Paragraph(data.upi_id, body8)])

    bank_inner_cells = [[Paragraph("<b>Bank Details</b>", section_hdr), Paragraph("", section_hdr)]]
    if bank_lines:
        bank_table_l = Table(bank_lines, colWidths=[22*mm])
        qr_cell = [_qr_drawing(f"upi://pay?pa={data.upi_id}&pn={data.company_name}&am={float(data.total_amount):.2f}", 24*mm), Paragraph("Pay using UPI", ParagraphStyle("payupi", fontName=FONT_BOLD, fontSize=7, alignment=TA_CENTER))] if data.upi_id else [Paragraph("", small)]
        bank_row = Table([[bank_table_l, qr_cell]], colWidths=[45*mm, 45*mm])
    else:
        bank_row = Table([[Paragraph("—", small)]], colWidths=[90*mm])

    tnc_cell = Paragraph(f"<b>Terms and Conditions</b><br/>{(data.terms_conditions or '—').replace(chr(10), '<br/>')}", small)

    bank_box = Table([[Paragraph("<b>Bank Details</b>", section_hdr)], [bank_row], [Spacer(1,2)], [tnc_cell]], colWidths=[110*mm])
    bank_box.setStyle(TableStyle([("BOX",(0,0),(-1,-1),1,BORDER), ("LINEBELOW",(0,0),(-1,0),0.5,BORDER),
                                   ("TOPPADDING",(0,0),(-1,-1),4), ("BOTTOMPADDING",(0,0),(-1,-1),4)]))

    sig_box = Table([
        [Paragraph("Certified that the particulars given above are true and correct.", ParagraphStyle("cert", fontName=FONT_REGULAR, fontSize=7, alignment=TA_CENTER))],
        [Paragraph(f"<b>For {data.company_name}</b>", ParagraphStyle("forco", fontName=FONT_BOLD, fontSize=9, alignment=TA_CENTER))],
        [Spacer(1, 14*mm)],
        [Paragraph("This is a computer generated invoice.<br/>No signature required.", ParagraphStyle("stamp", fontName=FONT_REGULAR, fontSize=6.5, alignment=TA_CENTER, textColor=colors.HexColor("#999999")))],
        [Paragraph("Authorised Signatory", ParagraphStyle("sig", fontName=FONT_REGULAR, fontSize=8, alignment=TA_CENTER))],
    ], colWidths=[73*mm])
    sig_box.setStyle(TableStyle([("BOX",(0,0),(-1,-1),1,BORDER), ("TOPPADDING",(0,0),(-1,-1),5), ("BOTTOMPADDING",(0,0),(-1,-1),5)]))

    bottom_row = Table([[bank_box, sig_box]], colWidths=[110*mm, 73*mm])
    bottom_row.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"), ("LEFTPADDING",(0,0),(-1,-1),0), ("RIGHTPADDING",(0,0),(-1,-1),0)]))
    story.append(bottom_row)
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph("Thank you for your business!", ParagraphStyle("thanks", fontName=FONT_REGULAR, fontSize=9)))

    def _page_footer(canvas, doc_):
        canvas.saveState()
        page_w, _ = A4
        canvas.setFillColor(colors.HexColor("#999999"))
        canvas.setFont(FONT_REGULAR, 6.5)
        canvas.drawRightString(page_w - 8*mm, 5*mm, f"Page {doc_.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    return buffer.getvalue()


# ── Font setup: register Noto Sans for proper ₹ glyph + clean typography ──────
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.graphics.shapes import Drawing, String
from reportlab.graphics.charts.barcharts import HorizontalBarChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.legends import Legend
from reportlab.lib.pagesizes import A4 as A4_SIZE

FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"
try:
    pdfmetrics.registerFont(TTFont("NotoSans", "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf"))
    pdfmetrics.registerFont(TTFont("NotoSans-Bold", "/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf"))
    FONT_REGULAR = "NotoSans"
    FONT_BOLD = "NotoSans-Bold"
except Exception:
    pass  # falls back to Helvetica (no ₹ glyph) if the font isn't installed yet

BRAND_ACCENT = colors.HexColor("#00C2A8")
BG_SOFT      = colors.HexColor("#F0F4FA")
GREEN        = colors.HexColor("#0E9F6E")
ORANGE       = colors.HexColor("#E8720C")
RED          = colors.HexColor("#DC2626")


def format_inr(amount) -> str:
    """Indian numbering with non-breaking currency symbol: ₹17,84,963.00"""
    amount = float(amount or 0)
    neg = amount < 0
    amount = abs(amount)
    whole, _, frac = f"{amount:,.2f}".partition(".")
    whole = whole.replace(",", "")
    if len(whole) > 3:
        last3, rest = whole[-3:], whole[:-3]
        groups = []
        while len(rest) > 2:
            groups.insert(0, rest[-2:])
            rest = rest[:-2]
        if rest:
            groups.insert(0, rest)
        whole = ",".join(groups) + "," + last3
    symbol = "\u20b9" if FONT_REGULAR == "NotoSans" else "Rs."
    sep = "" if symbol == "\u20b9" else "\u00a0"  # non-breaking space keeps "Rs." glued to the number
    return f"{'-' if neg else ''}{symbol}{sep}{whole}.{frac}"


def _header_footer(canvas, doc, title: str, company: dict, period: str, generated_by: str):
    canvas.saveState()
    page_w, page_h = A4_SIZE

    canvas.setFillColor(BRAND_DARK)
    canvas.rect(0, page_h - 34*mm, page_w, 34*mm, fill=1, stroke=0)

    # Left block — company identity
    x = 16*mm
    canvas.setFillColor(colors.white)
    canvas.setFont(FONT_BOLD, 15)
    canvas.drawString(x, page_h - 12*mm, company.get("legal_name") or "Company")
    canvas.setFont(FONT_REGULAR, 8)
    canvas.setFillColor(colors.HexColor("#B8C4D9"))
    line_y = page_h - 17*mm
    details = []
    if company.get("reg_address"): details.append(company["reg_address"][:60])
    if company.get("gstin"): details.append(f"GSTIN: {company['gstin']}")
    contact_bits = [b for b in [company.get("phone"), company.get("email"), company.get("website")] if b]
    if contact_bits: details.append(" · ".join(contact_bits))
    for line in details[:3]:
        canvas.drawString(x, line_y, line)
        line_y -= 4*mm

    # Right block — report metadata
    rx = page_w - 16*mm
    canvas.setFont(FONT_BOLD, 12)
    canvas.setFillColor(BRAND_ACCENT)
    canvas.drawRightString(rx, page_h - 12*mm, title)
    canvas.setFont(FONT_REGULAR, 8)
    canvas.setFillColor(colors.HexColor("#B8C4D9"))
    meta_lines = [
        f"Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}",
        f"Period: {period}",
        f"Generated By: {generated_by}",
    ]
    my = page_h - 17*mm
    for line in meta_lines:
        canvas.drawRightString(rx, my, line)
        my -= 4*mm

    # Footer
    canvas.setFillColor(colors.HexColor("#999999"))
    canvas.setFont(FONT_REGULAR, 7.5)
    canvas.drawString(16*mm, 10*mm, "Generated by VyaparPro ERP")
    canvas.drawCentredString(page_w/2, 10*mm, "Confidential – Internal Use Only")
    canvas.drawRightString(page_w - 16*mm, 10*mm, f"Page {doc.page}")
    canvas.setStrokeColor(MED_GREY)
    canvas.line(16*mm, 14*mm, page_w - 16*mm, 14*mm)
    canvas.restoreState()


def _kpi_cards(summary: list[tuple[str, str, str]]) -> Table:
    """summary: list of (label, value, accent) where accent in {'blue','green','orange','red'}"""
    accent_map = {"blue": BRAND_BLUE, "green": GREEN, "orange": ORANGE, "red": RED}
    cells, styles = [], []
    for i, (label, value, accent) in enumerate(summary):
        color = accent_map.get(accent, BRAND_BLUE)
        cell = Table([[Paragraph(f'<font color="#666666" size="8">{label.upper()}</font>')],
                      [Paragraph(f'<font color="{color.hexval()}" size="12"><b>{value}</b></font>')]],
                     colWidths=[48*mm])
        cell.setStyle(TableStyle([
            ("TOPPADDING", (0,0), (-1,-1), 8), ("BOTTOMPADDING", (0,0), (-1,-1), 8),
            ("LEFTPADDING", (0,0), (-1,-1), 10), ("BACKGROUND", (0,0), (-1,-1), BG_SOFT),
            ("LINEBELOW", (0,0), (-1,0), 2.5, color), ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ]))
        cells.append(cell)
    row = Table([cells], colWidths=[50*mm]*len(cells))
    row.setStyle(TableStyle([("LEFTPADDING",(0,0),(-1,-1),0), ("RIGHTPADDING",(0,0),(-1,-1),3),
                              ("TOPPADDING",(0,0),(-1,-1),0), ("BOTTOMPADDING",(0,0),(-1,-1),0)]))
    return row


def _bar_chart(categories: list[str], values: list[float], title: str) -> Drawing:
    n = len(categories)
    max_val = max(values) if values else 1
    longest_label = max((len(c) for c in categories), default=10)
    left_margin = min(max(35*mm, longest_label * 1.6*mm), 65*mm)
    bar_h = 6*mm
    chart_height = n * bar_h + 10*mm
    chart_width = 170*mm - left_margin - 20*mm  # reserve room for value labels past bar end

    d = Drawing(170*mm, chart_height + 8*mm)
    chart = HorizontalBarChart()
    chart.x, chart.y = left_margin, 5*mm
    chart.width, chart.height = chart_width, n * bar_h
    chart.data = [values]
    chart.categoryAxis.categoryNames = categories
    chart.categoryAxis.labels.fontName = FONT_REGULAR
    chart.categoryAxis.labels.fontSize = 7.5
    chart.categoryAxis.labels.maxWidth = left_margin - 4*mm
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = max_val * 1.25 if max_val else 1
    chart.valueAxis.labels.fontName = FONT_REGULAR
    chart.valueAxis.labels.fontSize = 7
    chart.bars[0].fillColor = BRAND_BLUE
    chart.barWidth = bar_h * 0.65
    chart.barSpacing = bar_h * 0.35
    d.add(chart)

    # Draw value labels manually, past the end of each bar — never inside, never clipped
    for i, val in enumerate(values):
        bar_len = (val / chart.valueAxis.valueMax) * chart_width if chart.valueAxis.valueMax else 0
        y = chart.y + i * bar_h + bar_h * 0.32
        label = format_inr(val) if val >= 1000 else f"{val:.0f}"
        d.add(String(chart.x + bar_len + 3*mm, y, label, fontName=FONT_REGULAR, fontSize=7, fillColor=BRAND_DARK))
    return d


def _pie_chart(labels: list[str], values: list[float]) -> Drawing:
    palette = [BRAND_BLUE, GREEN, ORANGE, BRAND_ACCENT, RED, colors.HexColor("#8B5CF6"), colors.HexColor("#EC4899")]
    d = Drawing(170*mm, 55*mm)
    pie = Pie()
    pie.x, pie.y = 20*mm, 5*mm
    pie.width, pie.height = 45*mm, 45*mm
    pie.data = values
    pie.labels = None
    for i in range(len(values)):
        pie.slices[i].fillColor = palette[i % len(palette)]
        pie.slices[i].strokeColor = colors.white
        pie.slices[i].strokeWidth = 1
    d.add(pie)
    legend = Legend()
    legend.x, legend.y = 75*mm, 40*mm
    legend.dx, legend.dy = 3*mm, 3*mm
    legend.fontName = FONT_REGULAR
    legend.fontSize = 8
    legend.colorNamePairs = [(palette[i % len(palette)], f"{labels[i][:20]} ({values[i]:.0f})") for i in range(len(values))]
    d.add(legend)
    return d


def generate_report_pdf(title: str, subtitle: str, summary: list, tables: list,
                         company: dict | None = None, period: str = "",
                         generated_by: str = "System", bar_chart: dict | None = None,
                         pie_chart: dict | None = None) -> bytes:
    """
    summary: list of (label, value) OR (label, value, accent) tuples
    tables:  list of (section_title, headers, rows)
    bar_chart: {"title": str, "categories": [...], "values": [...]} or None
    pie_chart: {"labels": [...], "values": [...]} or None
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=40*mm, bottomMargin=20*mm,
                             leftMargin=16*mm, rightMargin=16*mm)
    styles = getSampleStyleSheet()
    section_style = ParagraphStyle("RSection", fontName=FONT_BOLD, fontSize=12,
                                    textColor=BRAND_DARK, spaceBefore=16, spaceAfter=8)

    story = [Spacer(1, 4*mm)]

    if summary:
        summary_norm = [(s if len(s) == 3 else (*s, "blue")) for s in summary]
        story.append(_kpi_cards(summary_norm))
        story.append(Spacer(1, 6*mm))

    if bar_chart and bar_chart.get("values"):
        story.append(Paragraph(bar_chart.get("title", "Overview"), section_style))
        story.append(_bar_chart(bar_chart["categories"], bar_chart["values"], bar_chart.get("title", "")))
        story.append(Spacer(1, 4*mm))

    if pie_chart and pie_chart.get("values"):
        story.append(Paragraph(pie_chart.get("title", "Distribution"), section_style))
        story.append(_pie_chart(pie_chart["labels"], pie_chart["values"]))
        story.append(Spacer(1, 4*mm))

    for section_title, headers, rows in tables:
        story.append(Paragraph(section_title, section_style))
        if not rows:
            story.append(Paragraph("No data for this period", styles["Normal"]))
            continue
        data = [headers] + rows
        col_width = doc.width / len(headers)
        t = Table(data, colWidths=[col_width]*len(headers), repeatRows=1)
        style = [
            ("BACKGROUND", (0,0), (-1,0), BRAND_DARK),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), FONT_BOLD),
            ("FONTNAME", (0,1), (-1,-1), FONT_REGULAR),
            ("FONTSIZE", (0,0), (-1,-1), 8.5),
            ("GRID", (0,0), (-1,-1), 0.4, MED_GREY),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, BG_SOFT]),
            ("TOPPADDING", (0,0), (-1,-1), 6), ("BOTTOMPADDING", (0,0), (-1,-1), 6),
            ("ALIGN", (1,1), (-1,-1), "RIGHT"),
        ]
        t.setStyle(TableStyle(style))
        story.append(t)
        story.append(Spacer(1, 4*mm))

    def _on_page(canvas, doc_):
        _header_footer(canvas, doc_, title, company or {}, period, generated_by)

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    return buf.getvalue()