"""add transporter_id and vehicle_no to invoices

Revision ID: 38bfca197a4d
Revises: f582646e8b1b
Create Date: 2026-07-26 16:55:57.789613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38bfca197a4d'
down_revision: Union[str, Sequence[str], None] = 'f582646e8b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('transporter_id', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('vehicle_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'vehicle_no')
    op.drop_column('invoices', 'transporter_id')
    # ### end Alembic commands ###
