"""initial

Revision ID: b0a10fb064de
Revises: 
Create Date: 2026-06-13 16:56:51.769687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0a10fb064de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gst_rates',
    sa.Column('rate_name', sa.String(length=30), nullable=False),
    sa.Column('total_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applicable_from', sa.Date(), nullable=True),
    sa.Column('applicable_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('total_rate')
    )
    op.create_table('organizations',
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('org_type', sa.String(length=30), nullable=False),
    sa.Column('parent_org_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('perm_code', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perm_code')
    )
    op.create_table('units_of_measure',
    sa.Column('uom_code', sa.String(length=10), nullable=False),
    sa.Column('uom_name', sa.String(length=40), nullable=False),
    sa.Column('base_unit_id', sa.UUID(), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uom_code')
    )
    op.create_table('companies',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('tan', sa.String(length=10), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('reg_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('financial_year_start', sa.SmallInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('po_prefix', sa.String(length=20), nullable=False),
    sa.Column('jo_prefix', sa.String(length=20), nullable=False),
    sa.Column('quote_prefix', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_table('hsn_master',
    sa.Column('hsn_code', sa.String(length=8), nullable=False),
    sa.Column('hsn_description', sa.Text(), nullable=True),
    sa.Column('chapter', sa.String(length=2), nullable=True),
    sa.Column('heading', sa.String(length=4), nullable=True),
    sa.Column('sub_heading', sa.String(length=6), nullable=True),
    sa.Column('tariff_item', sa.String(length=8), nullable=True),
    sa.Column('gst_rate_id', sa.UUID(), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['gst_rate_id'], ['gst_rates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hsn_code')
    )
    op.create_table('branches',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_code', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=150), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('branch_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_code')
    )
    op.create_table('product_categories',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cat_name', sa.String(length=100), nullable=False),
    sa.Column('parent_cat_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_cat_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=60), nullable=False),
    sa.Column('role_level', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'role_name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('perm_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['perm_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'perm_id')
    )
    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('failed_logins', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email')
    )
    op.create_table('audit_log',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_ref', sa.String(length=50), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('party_type', sa.String(length=10), nullable=False),
    sa.Column('party_code', sa.String(length=30), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('party_category', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alt_phone', sa.String(length=20), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('billing_city', sa.String(length=80), nullable=True),
    sa.Column('billing_state', sa.String(length=80), nullable=True),
    sa.Column('billing_state_code', sa.String(length=2), nullable=True),
    sa.Column('billing_pincode', sa.String(length=10), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_days', sa.SmallInteger(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_type', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cat_id', sa.UUID(), nullable=True),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model_no', sa.String(length=80), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('hsn_code', sa.String(length=8), nullable=True),
    sa.Column('sac_code', sa.String(length=6), nullable=True),
    sa.Column('uom_id', sa.UUID(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_selling_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('batch_tracking', sa.Boolean(), nullable=False),
    sa.Column('serial_tracking', sa.Boolean(), nullable=False),
    sa.Column('expiry_tracking', sa.Boolean(), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reorder_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_demand_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_code')
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_contacts',
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_code', sa.String(length=40), nullable=False),
    sa.Column('variant_name', sa.String(length=200), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'variant_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variants')
    op.drop_table('party_contacts')
    op.drop_table('user_sessions')
    op.drop_table('products')
    op.drop_table('parties')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('product_categories')
    op.drop_table('branches')
    op.drop_table('hsn_master')
    op.drop_table('companies')
    op.drop_table('units_of_measure')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_table('gst_rates')
    # ### end Alembic commands ###
